# Generated by Django 6.0.1 on 2026-02-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_desk', '0003_ticket_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='ticket-attachments/'),
        ),
    ]
