# Generated by Django 6.0.1 on 2026-01-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_desk', '0003_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
