# Generated by Django 6.0.1 on 2026-02-15 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_desk', '0004_alter_ticket_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_status', to='service_desk.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ticket', 'user')},
            },
        ),
    ]
