# Generated by Django 6.0.1 on 2026-01-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_desk', '0004_ticket_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(blank=True, editable=False, max_length=15, unique=True),
        ),
    ]
