# Generated by Django 6.0.1 on 2026-02-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_desk', '0005_ticketreadstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='tickets/attachments/%Y/%m/%d'),
        ),
    ]
