# Generated by Django 6.0.1 on 2026-01-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_desk', '0006_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firm',
            old_name='DIC',
            new_name='dic',
        ),
        migrations.RenameField(
            model_name='firm',
            old_name='IC',
            new_name='ic',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Critical')], default=2),
        ),
    ]
