# Generated by Django 6.0.1 on 2026-02-28 09:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_desk', '0007_remove_ticket_attachment_ticketattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
