# Generated by Django 6.0.1 on 2026-03-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_desk', '0008_ticket_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
