# Generated by Django 6.0.1 on 2026-03-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_desk', '0009_record_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
    ]
