# Generated by Django 6.0.1 on 2026-03-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_desk', '0010_record_is_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='last_update_internal',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
