# Generated by Django 6.0.1 on 2026-03-15 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_desk', '0011_ticket_last_update_internal_alter_ticket_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_updated_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_updated_by_internal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_updated_internal_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
