# Generated by Django 6.0.1 on 2026-03-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_desk', '0014_ticket_requester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='companies',
            field=models.ManyToManyField(related_name='users', to='service_desk.company'),
        ),
    ]
