# Generated by Django 6.0.1 on 2026-03-28 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_desk', '0015_alter_user_companies'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDeskSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_enabled', models.BooleanField(default=True)),
                ('central_notification_enabled', models.BooleanField(default=False)),
                ('agent_notification_enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDeskEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('service_desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='service_desk.servicedesksettings')),
            ],
        ),
    ]
